from flask import Flask, jsonify
import pandas as pd
import numpy as np

app = Flask(__name__)

@app.route('/api/process', methods=['GET'])
def process_handler():
    try:
        # ETAPA 0: DADOS COMPLETOS E EMBUTIDOS. O UNIVERSO COMPLETO DE PRODUTOS AGORA FAZ PARTE DO CÓDIGO.
        embedded_data = [
            {"codigo": "A", "produto": "BALA FREEGELLS SABORES 120UN", "estoque_atual": -445, "qtd_venda": 506},
            {"codigo": "A", "produto": "CIGARRO PALHEIRO PAULISTINHA PICADO", "estoque_atual": 24, "qtd_venda": 257},
            {"codigo": "A", "produto": "BALA MACIA SABORES 100 UN", "estoque_atual": -4, "qtd_venda": 229},
            {"codigo": "A", "produto": "CERVEJA AMSTEL 350ML", "estoque_atual": 301, "qtd_venda": 211},
            {"codigo": "A", "produto": "CERVEJA HEINEKEN LONG", "estoque_atual": 480, "qtd_venda": 202},
            {"codigo": "A", "produto": "CERVEJA BAVARIA 350ML", "estoque_atual": 72, "qtd_venda": 136},
            {"codigo": "A", "produto": "CIGARRO PALHEIRO PIRACANJUBA PICADO", "estoque_atual": 177, "qtd_venda": 128},
            {"codigo": "A", "produto": "CERVEJA AMSTEL 269ML", "estoque_atual": 213, "qtd_venda": 127},
            {"codigo": "A", "produto": "AGUA COM GAS LIA 500ML", "estoque_atual": 115, "qtd_venda": 118},
            {"codigo": "A", "produto": "REFRI COCA COLA 2L", "estoque_atual": 79, "qtd_venda": 118},
            {"codigo": "A", "produto": "CERVEJA ANTARTICA 350ML (AMBEV)", "estoque_atual": 130, "qtd_venda": 117},
            {"codigo": "A", "produto": "CERVEJA HEINEKEN 350ML", "estoque_atual": 176, "qtd_venda": 114},
            {"codigo": "A", "produto": "CERVEJA SKOL PILSEN 269ML (AMBEV)", "estoque_atual": 96, "qtd_venda": 109},
            {"codigo": "A", "produto": "CIGARRO MALBORO RED SELECTION PICADO", "estoque_atual": 640, "qtd_venda": 104},
            {"codigo": "A", "produto": "BALA CARAMELO 100 UN", "estoque_atual": 27, "qtd_venda": 98},
            {"codigo": "A", "produto": "CIGARRO SAN MARINO PICADO", "estoque_atual": 360, "qtd_venda": 97},
            {"codigo": "A", "produto": "SALGADO", "estoque_atual": -12, "qtd_venda": 96},
            {"codigo": "A", "produto": "CHICLETE BIGBIG SABORES 89UN (GRILAO)", "estoque_atual": 215, "qtd_venda": 91},
            {"codigo": "A", "produto": "AGUA SEM GAS LIA 500ML", "estoque_atual": 42, "qtd_venda": 90},
            {"codigo": "A", "produto": "CERVEJA BRAHMA 350ML (AMBEV)", "estoque_atual": 82, "qtd_venda": 86},
            {"codigo": "A", "produto": "SEDA ZOMO PICADO", "estoque_atual": 2488, "qtd_venda": 85},
            {"codigo": "A", "produto": "DOCE PACOQUITA 100UN (GRILAO)", "estoque_atual": 77, "qtd_venda": 84},
            {"codigo": "A", "produto": "CHICLETE PLUTONITA AZEDO 40 UN", "estoque_atual": 177, "qtd_venda": 76},
            {"codigo": "A", "produto": "ISQUEIRO BIC PEQUENO", "estoque_atual": 116, "qtd_venda": 74},
            {"codigo": "A", "produto": "CIGARRO ROTHMANS MACO", "estoque_atual": 60, "qtd_venda": 69},
            {"codigo": "A", "produto": "CIGARRO DUNHIL AZUL", "estoque_atual": 50, "qtd_venda": 66},
            {"codigo": "A", "produto": "CERVEJA GLACIAL 350ML", "estoque_atual": 84, "qtd_venda": 63},
            {"codigo": "A", "produto": "CIGARRO ROTHMANS LARANJA", "estoque_atual": 110, "qtd_venda": 61},
            {"codigo": "A", "produto": "CHICLETE POOSH 40UN", "estoque_atual": -13, "qtd_venda": 59},
            {"codigo": "A", "produto": "CIGARRO ROTHMANS VERDE", "estoque_atual": 70, "qtd_venda": 59},
            {"codigo": "A", "produto": "CIGARRO DUNHIL VERMELHO", "estoque_atual": 40, "qtd_venda": 55},
            {"codigo": "A", "produto": "CIGARRO LUCKY STRIKE VERMELHO", "estoque_atual": 130, "qtd_venda": 55},
            {"codigo": "A", "produto": "PIPOCA DOCE 15G", "estoque_atual": 0, "qtd_venda": 54},
            {"codigo": "A", "produto": "CIGARRO EIGHT MACO", "estoque_atual": 70, "qtd_venda": 53},
            {"codigo": "A", "produto": "CIGARRO PALHEIRO SOUZA PAIOL PICADO", "estoque_atual": 137, "qtd_venda": 52},
            {"codigo": "A", "produto": "SALGAMINHO 40G", "estoque_atual": -12, "qtd_venda": 52},
            {"codigo": "A", "produto": "DOCE PE DE MOLEQUE 50UN (GRILAO)", "estoque_atual": 16, "qtd_venda": 51},
            {"codigo": "A", "produto": "CIGARRO ROTHMANS AZUL", "estoque_atual": 60, "qtd_venda": 51},
            {"codigo": "A", "produto": "ENERGETICO MONSTER", "estoque_atual": 64, "qtd_venda": 51},
            {"codigo": "A", "produto": "CIGARRO LUCKY STRIKE 2 BOLAS", "estoque_atual": "22,25", "qtd_venda": 49},
            {"codigo": "B", "produto": "HALLS", "estoque_atual": 111, "qtd_venda": 48},
            {"codigo": "B", "produto": "REFRI GUARANA 2L", "estoque_atual": 11, "qtd_venda": 47},
            {"codigo": "B", "produto": "CERVEJA BUDWEISER 350ML", "estoque_atual": 36, "qtd_venda": 46},
            {"codigo": "B", "produto": "CIGARRO GUDAN", "estoque_atual": 30, "qtd_venda": 46},
            {"codigo": "B", "produto": "TRIDENT", "estoque_atual": 150, "qtd_venda": 46},
            {"codigo": "B", "produto": "SALGADINHO SABORES", "estoque_atual": 0, "qtd_venda": 45},
            {"codigo": "B", "produto": "CIGARRO PALHEIRO JACK PAIOLS PICADO", "estoque_atual": 89, "qtd_venda": 42},
            {"codigo": "B", "produto": "CERVEJA BRAHMA DUPLO MALTE 350ML (AMBEV)", "estoque_atual": 7, "qtd_venda": 40},
            {"codigo": "B", "produto": "CARVAO 3 KG", "estoque_atual": 48, "qtd_venda": 40},
            {"codigo": "B", "produto": "PAO DE ALHO", "estoque_atual": 50, "qtd_venda": 40},
            {"codigo": "B", "produto": "CIGARRO GIFT MACO", "estoque_atual": 150, "qtd_venda": 39},
            {"codigo": "B", "produto": "PIRULITO BIG BIG", "estoque_atual": -18, "qtd_venda": 39},
            {"codigo": "B", "produto": "CIGARRO LUCKY STRIKE AZUL", "estoque_atual": 50, "qtd_venda": 38},
            {"codigo": "B", "produto": "CHOCOLATE LAKA", "estoque_atual": 14, "qtd_venda": 37},
            {"codigo": "B", "produto": "CIGARRO ROTHMANS CINZA", "estoque_atual": 20, "qtd_venda": 36},
            {"codigo": "B", "produto": "SUCO KAPO", "estoque_atual": 33, "qtd_venda": 36},
            {"codigo": "B", "produto": "AGUA DE COCO", "estoque_atual": 61, "qtd_venda": 35},
            {"codigo": "B", "produto": "CIGARRO DUNHIL PRATA", "estoque_atual": 50, "qtd_venda": 35},
            {"codigo": "B", "produto": "VODKA KISLLA", "estoque_atual": 17, "qtd_venda": 34},
            {"codigo": "B", "produto": "CIGARRO L&M", "estoque_atual": 110, "qtd_venda": 33},
            {"codigo": "B", "produto": "GELO CUBP 3KG", "estoque_atual": 17, "qtd_venda": 33},
            {"codigo": "B", "produto": "CIGARRO PALHEIRO UNIVERSO PICADO", "estoque_atual": 48, "qtd_venda": 32},
            {"codigo": "B", "produto": "CERVEJA IMPERIO 350ML", "estoque_atual": 48, "qtd_venda": 31},
            {"codigo": "B", "produto": "VINHO QUINTA DO MORGADO", "estoque_atual": 23, "qtd_venda": 31},
            {"codigo": "B", "produto": "AMENDOIM JAPONES", "estoque_atual": -3, "qtd_venda": 30},
            {"codigo": "B", "produto": "CERVEJA DEVASSA 350ML", "estoque_atual": -12, "qtd_venda": 30},
            {"codigo": "B", "produto": "DOCE FINI", "estoque_atual": 51, "qtd_venda": 29},
            {"codigo": "B", "produto": "GELO DE COCO", "estoque_atual": 74, "qtd_venda": 29},
            {"codigo": "B", "produto": "SKINKA", "estoque_atual": 42, "qtd_venda": 28},
            {"codigo": "B", "produto": "SUCO PRATS LARANJA 330ML", "estoque_atual": 12, "qtd_venda": 28},
            {"codigo": "B", "produto": "CHOCOLATE HERSHEYS", "estoque_atual": -1, "qtd_venda": 26},
            {"codigo": "B", "produto": "CIGARRO CHESTERFIELD", "estoque_atual": 100, "qtd_venda": 26},
            {"codigo": "B", "produto": "PIRULITO CORACAO", "estoque_atual": -14, "qtd_venda": 26},
            {"codigo": "B", "produto": "SALGADINHO TORCIDA", "estoque_atual": -1, "qtd_venda": 26},
            {"codigo": "B", "produto": "CHOCOLATE DIAMANTE NEGRO", "estoque_atual": 15, "qtd_venda": 25},
            {"codigo": "B", "produto": "CIGARRO CAMEL", "estoque_atual": 70, "qtd_venda": 25},
            {"codigo": "B", "produto": "RED BULL", "estoque_atual": 37, "qtd_venda": 24},
            {"codigo": "B", "produto": "REFRI FANTA 2L", "estoque_atual": 24, "qtd_venda": 23},
            {"codigo": "B", "produto": "CIGARRO PALHEIRO CAPIROTO PICADO", "estoque_atual": 59, "qtd_venda": 22},
            {"codigo": "B", "produto": "SUCO TIAL", "estoque_atual": -7, "qtd_venda": 22},
            {"codigo": "C", "produto": "CACHAÇA VELHO BARREIRO", "estoque_atual": 11, "qtd_venda": 21},
            {"codigo": "C", "produto": "CERVEJA PETRA 350ML", "estoque_atual": 12, "qtd_venda": 21},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO TERERE PICADO", "estoque_atual": 20, "qtd_venda": 21},
            {"codigo": "C", "produto": "CERVEJA HEINEKEN ZERO", "estoque_atual": 92, "qtd_venda": 20},
            {"codigo": "C", "produto": "CHICLETE MENTOS", "estoque_atual": 24, "qtd_venda": 20},
            {"codigo": "C", "produto": "CHOCOLATE PRESTIGIO", "estoque_atual": 2, "qtd_venda": 20},
            {"codigo": "C", "produto": "CONHAQUE DOMUS", "estoque_atual": 11, "qtd_venda": 20},
            {"codigo": "C", "produto": "SALGADINHO FANDANGOS", "estoque_atual": -2, "qtd_venda": 20},
            {"codigo": "C", "produto": "CHOCOLATE OURO BRANCO", "estoque_atual": -1, "qtd_venda": 19},
            {"codigo": "C", "produto": "CIGARRO ROTHMANS VERMELHO", "estoque_atual": 10, "qtd_venda": 19},
            {"codigo": "C", "produto": "VODKA SLOVADA", "estoque_atual": 5, "qtd_venda": 19},
            {"codigo": "C", "produto": "CERVEJA EISENBAHN 350ML", "estoque_atual": 2, "qtd_venda": 18},
            {"codigo": "C", "produto": "CHOCOLATE BIBIS", "estoque_atual": -8, "qtd_venda": 18},
            {"codigo": "C", "produto": "CHOCOLATE SONHO DE VALSA", "estoque_atual": -1, "qtd_venda": 18},
            {"codigo": "C", "produto": "ENGETICO VULCANO", "estoque_atual": 1, "qtd_venda": 18},
            {"codigo": "C", "produto": "PIPOCA", "estoque_atual": 0, "qtd_venda": 18},
            {"codigo": "C", "produto": "REFRI COCA COLA 1L", "estoque_atual": 23, "qtd_venda": 18},
            {"codigo": "C", "produto": "AMENDOIM GRELHADITOS", "estoque_atual": -7, "qtd_venda": 17},
            {"codigo": "C", "produto": "CERVEJA SPATEN 350ML", "estoque_atual": 24, "qtd_venda": 17},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO EXTRA FORTE PICADO", "estoque_atual": 20, "qtd_venda": 17},
            {"codigo": "C", "produto": "SALGADINHO CHEETOS", "estoque_atual": -3, "qtd_venda": 17},
            {"codigo": "C", "produto": "CATUABA SELVAGEM", "estoque_atual": 11, "qtd_venda": 16},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO MAMA CADELA PICADO", "estoque_atual": 9, "qtd_venda": 16},
            {"codigo": "C", "produto": "REFRI PEPSI 2L", "estoque_atual": 12, "qtd_venda": 16},
            {"codigo": "C", "produto": "SUCO SUFRESH", "estoque_atual": -2, "qtd_venda": 16},
            {"codigo": "C", "produto": "BARRA DE CEREAL", "estoque_atual": 11, "qtd_venda": 15},
            {"codigo": "C", "produto": "CACHAÇA 51", "estoque_atual": 11, "qtd_venda": 15},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO VELHO CHICO PICADO", "estoque_atual": 40, "qtd_venda": 15},
            {"codigo": "C", "produto": "JURUPINGA", "estoque_atual": 12, "qtd_venda": 15},
            {"codigo": "C", "produto": "PIRULITO 7 BELO", "estoque_atual": 0, "qtd_venda": 15},
            {"codigo": "C", "produto": "PIRULITO FRUTAS", "estoque_atual": 0, "qtd_venda": 15},
            {"codigo": "C", "produto": "CACHAÇA PITU", "estoque_atual": 6, "qtd_venda": 14},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO GUDANG PICADO", "estoque_atual": 20, "qtd_venda": 14},
            {"codigo": "C", "produto": "SUCO PRATS LARANJA 900ML", "estoque_atual": 16, "qtd_venda": 14},
            {"codigo": "C", "produto": "SUCO DEL VALE", "estoque_atual": 11, "qtd_venda": 13},
            {"codigo": "C", "produto": "SUCO TANG", "estoque_atual": -33, "qtd_venda": 13},
            {"codigo": "C", "produto": "CACHAÇA JAMEL", "estoque_atual": 11, "qtd_venda": 12},
            {"codigo": "C", "produto": "CERVEJA STELLA 350ML", "estoque_atual": 1, "qtd_venda": 12},
            {"codigo": "C", "produto": "CHOCOLATE", "estoque_atual": 0, "qtd_venda": 12},
            {"codigo": "C", "produto": "CHOCOLATE LACTA", "estoque_atual": 0, "qtd_venda": 12},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO CALIFORNI PICADO", "estoque_atual": 20, "qtd_venda": 12},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO DUNHA PICADO", "estoque_atual": 10, "qtd_venda": 12},
            {"codigo": "C", "produto": "GIN", "estoque_atual": 0, "qtd_venda": 12},
            {"codigo": "C", "produto": "GOMAS", "estoque_atual": 0, "qtd_venda": 12},
            {"codigo": "C", "produto": "GELO BARRA 10KG", "estoque_atual": 0, "qtd_venda": 11},
            {"codigo": "C", "produto": "VODKA ASKOV", "estoque_atual": 11, "qtd_venda": 11},
            {"codigo": "C", "produto": "WHISKY", "estoque_atual": 0, "qtd_venda": 11},
            {"codigo": "C", "produto": "AMENDOIM", "estoque_atual": 0, "qtd_venda": 10},
            {"codigo": "C", "produto": "BALA", "estoque_atual": 0, "qtd_venda": 10},
            {"codigo": "C", "produto": "CERVEJA", "estoque_atual": 0, "qtd_venda": 10},
            {"codigo": "C", "produto": "CERVEJA ITAIPAVA 350ML", "estoque_atual": 24, "qtd_venda": 10},
            {"codigo": "C", "produto": "CHOCOLATE GAROTO", "estoque_atual": 0, "qtd_venda": 10},
            {"codigo": "C", "produto": "CIGARRO", "estoque_atual": 0, "qtd_venda": 10},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO", "estoque_atual": 0, "qtd_venda": 10},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO CIGANO PICADO", "estoque_atual": 10, "qtd_venda": 10},
            {"codigo": "C", "produto": "GELO", "estoque_atual": 0, "qtd_venda": 10},
            {"codigo": "C", "produto": "PIRULITO POP", "estoque_atual": -4, "qtd_venda": 10},
            {"codigo": "C", "produto": "SALGADO DE MILHO", "estoque_atual": -2, "qtd_venda": 10},
            {"codigo": "C", "produto": "SEDA", "estoque_atual": 0, "qtd_venda": 10},
            {"codigo": "C", "produto": "VINHO", "estoque_atual": 0, "qtd_venda": 10},
            {"codigo": "C", "produto": "VODKA ORLOFF", "estoque_atual": 11, "qtd_venda": 10},
            {"codigo": "C", "produto": "WHISKY RED LABEL", "estoque_atual": 5, "qtd_venda": 10},
            {"codigo": "C", "produto": "BOMBOM", "estoque_atual": 0, "qtd_venda": 9},
            {"codigo": "C", "produto": "CACHAÇA", "estoque_atual": 0, "qtd_venda": 9},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO CRESPA PICADO", "estoque_atual": 10, "qtd_venda": 9},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO ZE ROZETA PICADO", "estoque_atual": 10, "qtd_venda": 9},
            {"codigo": "C", "produto": "REFRI SCHWEPPES", "estoque_atual": 11, "qtd_venda": 9},
            {"codigo": "C", "produto": "SUCO", "estoque_atual": 0, "qtd_venda": 9},
            {"codigo": "C", "produto": "VINHO GOES", "estoque_atual": 11, "qtd_venda": 9},
            {"codigo": "C", "produto": "AGUA", "estoque_atual": 0, "qtd_venda": 8},
            {"codigo": "C", "produto": "AGUA MINERAL COM GAS", "estoque_atual": 0, "qtd_venda": 8},
            {"codigo": "C", "produto": "CERVEJA ORIGINAL 300ML (AMBEV)", "estoque_atual": 2, "qtd_venda": 8},
            {"codigo": "C", "produto": "CHOCOLATE KINDER", "estoque_atual": 1, "qtd_venda": 8},
            {"codigo": "C", "produto": "DOCE", "estoque_atual": 0, "qtd_venda": 8},
            {"codigo": "C", "produto": "DOCE DE LEITE", "estoque_atual": 0, "qtd_venda": 8},
            {"codigo": "C", "produto": "GATORADE", "estoque_atual": 23, "qtd_venda": 8},
            {"codigo": "C", "produto": "GUARAVITA", "estoque_atual": 48, "qtd_venda": 8},
            {"codigo": "C", "produto": "REFRI", "estoque_atual": 0, "qtd_venda": 8},
            {"codigo": "C", "produto": "REFRI H2O", "estoque_atual": 12, "qtd_venda": 8},
            {"codigo": "C", "produto": "WHISKY CAVALO BRANCO", "estoque_atual": 5, "qtd_venda": 8},
            {"codigo": "C", "produto": "BALA FINI", "estoque_atual": -4, "qtd_venda": 7},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO DON CORLEONE PICADO", "estoque_atual": 10, "qtd_venda": 7},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO OURO DE MINAS PICADO", "estoque_atual": 10, "qtd_venda": 7},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO PAIA PICADO", "estoque_atual": 20, "qtd_venda": 7},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO SANTA FE PICADO", "estoque_atual": 10, "qtd_venda": 7},
            {"codigo": "C", "produto": "CONHAQUE", "estoque_atual": 0, "qtd_venda": 7},
            {"codigo": "C", "produto": "DOCE BANANADA", "estoque_atual": -2, "qtd_venda": 7},
            {"codigo": "C", "produto": "ENERGETICO", "estoque_atual": 0, "qtd_venda": 7},
            {"codigo": "C", "produto": "PIRULITO", "estoque_atual": 0, "qtd_venda": 7},
            {"codigo": "C", "produto": "VODKA", "estoque_atual": 0, "qtd_venda": 7},
            {"codigo": "C", "produto": "ABSINTO", "estoque_atual": 6, "qtd_venda": 6},
            {"codigo": "C", "produto": "AGUA MINERAL", "estoque_atual": 0, "qtd_venda": 6},
            {"codigo": "C", "produto": "CHICLETE", "estoque_atual": 0, "qtd_venda": 6},
            {"codigo": "C", "produto": "CIGARRO ELETRONICO", "estoque_atual": 0, "qtd_venda": 6},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO D ROZETA PICADO", "estoque_atual": 10, "qtd_venda": 6},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO PORRONCA PICADO", "estoque_atual": 30, "qtd_venda": 6},
            {"codigo": "C", "produto": "COROTE", "estoque_atual": -2, "qtd_venda": 6},
            {"codigo": "C", "produto": "GUARANA", "estoque_atual": 0, "qtd_venda": 6},
            {"codigo": "C", "produto": "REFRI FANTA 350ML", "estoque_atual": 12, "qtd_venda": 6},
            {"codigo": "C", "produto": "REFRI GUARANA 350ML", "estoque_atual": 24, "qtd_venda": 6},
            {"codigo": "C", "produto": "REFRI MINI", "estoque_atual": 0, "qtd_venda": 6},
            {"codigo": "C", "produto": "WHISKY JACK DANIELS", "estoque_atual": 5, "qtd_venda": 6},
            {"codigo": "C", "produto": "BARRA NUTS", "estoque_atual": 11, "qtd_venda": 5},
            {"codigo": "C", "produto": "BATATA", "estoque_atual": 0, "qtd_venda": 5},
            {"codigo": "C", "produto": "BATATA RUFFLES", "estoque_atual": -1, "qtd_venda": 5},
            {"codigo": "C", "produto": "CACHAÇA VELHO BARREIRO GOLD", "estoque_atual": 5, "qtd_venda": 5},
            {"codigo": "C", "produto": "CAFE", "estoque_atual": 0, "qtd_venda": 5},
            {"codigo": "C", "produto": "CAMPARI", "estoque_atual": 6, "qtd_venda": 5},
            {"codigo": "C", "produto": "CERVEJA IMPERIO 269ML", "estoque_atual": 24, "qtd_venda": 5},
            {"codigo": "C", "produto": "CIGARRO PALHEIRO PONTEIO PICADO", "estoque_atual": 10, "qtd_venda": 5},
            {"codigo": "C", "produto": "COPO", "estoque_atual": 0, "qtd_venda": 5},
            {"codigo": "C", "produto": "DOCE DE ABACAXI", "estoque_atual": 0, "qtd_venda": 5},
            {"codigo": "C", "produto": "ENERGETICO TNT", "estoque_atual": 22, "qtd_venda": 5},
            {"codigo": "C", "produto": "GELO CUBP 5KG", "estoque_atual": 24, "qtd_venda": 5},
            {"codigo": "C", "produto": "GIN TONICA", "estoque_atual": 0, "qtd_venda": 5},
            {"codigo": "C", "produto": "MENTOS", "estoque_atual": 0, "qtd_venda": 5},
            {"codigo": "C", "produto": "REFRI GUARANA 1L", "estoque_atual": 6, "qtd_venda": 5},
            {"codigo": "C", "produto": "SAKE", "estoque_atual": 0, "qtd_venda": 5},
            {"codigo": "C", "produto": "SMIRNOFF ICE", "estoque_atual": 24, "qtd_venda": 5},
            {"codigo": "C", "produto": "VODKA SMIRNOFF", "estoque_atual": 11, "qtd_venda": 5},
            {"codigo": "C", "produto": "WISK", "estoque_atual": 0, "qtd_venda": 5}
        ]
        
        df = pd.DataFrame(embedded_data)

        df.rename(columns={"produto": "produto", "codigo": "codigo"}, inplace=True)

        df['estoque_atual'] = pd.to_numeric(df['estoque_atual'], errors='coerce').fillna(0)
        df['qtd_venda'] = pd.to_numeric(df['qtd_venda'], errors='coerce').fillna(0)
        df = df[df['estoque_atual'] >= 0].copy()

        df['vdm'] = df['qtd_venda'] / 17
        df['estoque_alvo'] = df['vdm'] * 12
        df['estoque_alvo'] = df['estoque_alvo'].apply(np.ceil)
        df['quantidade_a_comprar'] = df['estoque_alvo'] - df['estoque_atual']
        df['quantidade_a_comprar'] = df['quantidade_a_comprar'].clip(lower=0).astype(int)

        lista_de_compras = df[df['quantidade_a_comprar'] > 0]
        
        resultado = lista_de_compras[['codigo', 'produto', 'quantidade_a_comprar']].sort_values(
            by='quantidade_a_comprar', ascending=False
        ).to_dict(orient='records')
        
        return jsonify(resultado)
    except Exception as e:
        return jsonify({"error": "Falha crítica de lógica interna.", "details": str(e)}), 500
